ignore:
  # Ignore cross-spawn vulnerabilities by CVE ID due to false positive
  # as grype looks at package-lock.json where it shows versions with
  # vulnerabilities, npm ls shows only 7.0.6 verion is used
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9232
  - vulnerability: CVE-2025-9231
  - vulnerability: CVE-2025-60876
  - vulnerability: GHSA-5j98-mcp5-4vw2
  - vulnerability: GHSA-r6q2-hw4h-h46w
  - vulnerability: GHSA-8qq5-rm4j-mr97
  - vulnerability: GHSA-34x7-hfp2-rc4v
  - vulnerability: GHSA-37qj-frw5-hhjh
  - vulnerability: GHSA-p5wg-g6qr-c7cg
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
