---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
    name: ml-api-adapter-deployment
    labels:
      app: ml-api-adapter
 spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: ml-api-adapter
      spec:
        containers:
          - name: ml-api-adapter
            image: mojaloop/ml-api-adapter:latest
            command: ["node", "src/api/index.js"]
            ports:
              - containerPort: 3000
              # - containerPort: 3001
            livenessProbe:
              httpGet:
                path: /health
                port: 3000
              initialDelaySeconds: 60
              periodSeconds: 10
            # securityContext:
            #   capabilities:
            #     add:
            #       - NET_ADMIN
            # envFrom:
            #   - configMapRef:
            #       name: ml-api-adapter-config-env
            env:
              - name: CLEDG_PORT
                valueFrom:
                  configMapKeyRef:
                    name: ml-api-adapter-config
                    key: server.port
              # - name: CLEDG_ADMIN_PORT
              #   valueFrom:
              #     configMapKeyRef:
              #       name: ml-api-adapter-config
              #       key: admin.port
              - name: CLEDG_HOSTNAME
                valueFrom:
                  configMapKeyRef:
                    name: ml-api-adapter-config
                    key: server.host
              - name: CLEDG_DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: ml-api-adapter-secret
                    key: db.uri
            volumeMounts:
            - name: config-volume
              mountPath: /opt/ml-api-adapter/config
          - name: ml-api-adapter-admin
            image: mojaloop/ml-api-adapter:latest
            command: ["node", "src/admin/index.js"]
            ports:
              # - containerPort: 3000
              - containerPort: 3001
            livenessProbe:
              httpGet:
                path: /health
                port: 3001
              initialDelaySeconds: 60
              periodSeconds: 10
            # securityContext:
            #   capabilities:
            #     add:
            #       - NET_ADMIN
            env:
              # - name: CLEDG_PORT
              #   valueFrom:
              #     configMapKeyRef:
              #       name: ml-api-adapter-config
              #       key: server.port
              - name: CLEDG_ADMIN_PORT
                valueFrom:
                  configMapKeyRef:
                    name: ml-api-adapter-config
                    key: admin.port
              - name: CLEDG_HOSTNAME
                valueFrom:
                  configMapKeyRef:
                    name: ml-api-adapter-config
                    key: server.host
              - name: CLEDG_DATABASE_URI
                valueFrom:
                  secretKeyRef:
                    name: ml-api-adapter-secret
                    key: db.uri
            volumeMounts:
            - name: config-volume
              mountPath: /opt/ml-api-adapter/config
        volumes:
          - name: config-volume
            configMap:
              name: ml-api-adapter-config
              items:
              - key: default.json
                path: default.json
              - key: knexfile.js
                path: knexfile.js
