apiVersion: v1
kind: Secret
metadata:
  name: ml-api-adapter-secret
  labels:
      app: ml-api-adapter
type: Opaque
data:
  # base64 encoded string - The connection string for the database the ml api adapter will use. Postgres is currently the only supported database.
  db.uri: cG9zdGdyZXM6Ly9jZW50cmFsX2xlZGdlcjpveU14Z1pDaHV1QGNlbnRyYWwtbGVkZ2VyLXBvc3RncmVzcWw6NTQzMi9jZW50cmFsX2xlZGdlcg==
