version: 2.1
setup: true
orbs:
  build: kalinkrustev/build@1.0.17
workflows:
  setup:
    jobs:
      - build/workflow:
          filters:
            tags:
              only: /v\d+(\.\d+){2}(-(snapshot|hotfix|perf)\.\d+)?/
